### ISSUE TITLE
Custom cell formatting

### ISSUE THREAD

**Issue by vincent-lg** [foutaise/texttable#72]
Hi,

I just came across this great tool and I'm happy to say it works as a charm on Windows.  I was expecting more difficulty, following the documentation.

I have a question that might be a bit contextual: I'm developing a text-based game and use color codes (usually small wrappers, like ANSI codes or similar).  The original text looks something like this:

    This is normal text.  The next part |ris in red|n.  Back to normal.

Here, `|r` is a prefix for the red text, and `|n` goes back to the normal text.

When using a table, I would like to be able to add colors in cells, but that creates two problems:

1. With color codes, the length of the cell is wrongly calculated.  This means that the entire table can shift, because `|rword|n` is just 4-character long when it ends up in the terminal.
2. Colors "bleed", if the cell is split.  If, for instance, I want to write in a cell `a |rred stocking|n`, should the split happen between `red` and `stocking`, it will bleed red on the next cell.  In theory it would be great if it added `|n` before the next cell, and went back to red afterward.

That sounds extremely specialized and I'm aware I'm asking a complicated question.  How would you advise me to code that (whether in a fork or simply as a side tool for me)?  I don't ask you to code anything, just tips on how to best do it while still aligning with your code.  Well, if you really wish to code something, of course, you're welcome to do so.

Thanks for this great tool.  I was really beginning to hack my own ineffective tools and wishing someone else had done the work.  As you did.  So thanks!

Vincent

**Comment by foutaise** [comment]
Hi @vincent-lg 

Thanks for your kind comment.

I don't plan to add color support, in order to keep the library as simple and portable as possible. cf https://github.com/foutaise/texttable/issues/14.

In order to add color support, you would mostly have to modify the len() and _len_cell() methods to discard the escape codes activating/disabling coloring in the computation of the length of cells, in order to get coloring supported.

Best regards.
